services:
  postgres:
    image: postgres:13.3
    container_name: java-postgres
    environment:
      POSTGRES_DB: financial_tracker
      POSTGRES_USER: danis
      POSTGRES_PASSWORD: danis
    ports:
      - "5432:5432"


  app:
    build: ./
    container_name: "springboot-financial-tracker-app"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://java-postgres:5432/financial_tracker"
    ports:
      - "8080:8080"
    depends_on:
      - postgres